coinbase:
  timeout: 5000

resilience4j:
  circuitbreaker:
    instances:
      coinbase:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 2
        waitDurationInOpenState: 5s
        failureRateThreshold: 80
  timelimiter:
    configs:
      default:
        timeoutDuration: 60s
        cancelRunningFuture: true